[opener]
edit = [
  { run = '${EDITOR:=nvim} "$@"', desc = "nvim", block = true, for = "unix" }, 
  { run = 'sudo $EDITOR "$@"', desc = "sudo nvim", block = true, for = "unix" },
]

pdf = [
  { run = 'zen-browser "$@"', desc = "Zen", block = true, for = "unix" },
]

image = [
  { run = 'feh "$@"', desc = "feh", for = "unix" }

]

video = [
  { run = 'vlc "$@"', desc = "vlc", for = "unix" }
]

[open]
prepend_rules = [
  { mime = "application/pdf", use = [ "pdf", "reveal" ] },
  { mime = "image/*", use = [ "image" ] },
  { mime = "video/*", use = [ "video" ] },
]